<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <parent>
    <artifactId>nms-agent-entity</artifactId>
    <groupId>org.terracotta.management</groupId>
    <version>5.10.29</version>
  </parent>
  <modelVersion>4.0.0</modelVersion>

  <artifactId>nms-agent-entity-common</artifactId>
  <name>Terracotta Management :: NMS Agent Entity :: Common</name>

  <dependencies>
    <!-- all these libs will be in common server classpath -->
    <dependency>
      <groupId>org.terracotta.management</groupId>
      <artifactId>management-model</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>org.terracotta.management</groupId>
      <artifactId>sequence-generator</artifactId>
      <version>${project.version}</version>
    </dependency>

    <!-- will be inside the entity jar -->
    <dependency>
      <groupId>org.terracotta.voltron.proxy</groupId>
      <artifactId>voltron-proxy-common</artifactId>
      <version>${project.version}</version>
    </dependency>
  </dependencies>

</project>