<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.terracotta.dynamic-config.server</groupId>
    <artifactId>dynamic-config-server</artifactId>
    <version>5.10.29</version>
    <relativePath>../pom.xml</relativePath>
  </parent>

  <artifactId>dynamic-config-configuration-repository</artifactId>
  <name>Dynamic Config :: Server :: Configuration Repository</name>

  <dependencies>
    <dependency>
      <groupId>org.terracotta.dynamic-config.server</groupId>
      <artifactId>dynamic-config-server-api</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>org.terracotta.dynamic-config</groupId>
      <artifactId>dynamic-config-api-json</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>org.terracotta.common</groupId>
      <artifactId>common-sanskrit</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>org.terracotta.common</groupId>
      <artifactId>common-nomad</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>org.terracotta</groupId>
      <artifactId>terracotta-utilities-tools</artifactId>
      <exclusions>
          <exclusion>
              <groupId>org.slf4j</groupId>
              <artifactId>slf4j-api</artifactId>
          </exclusion>
      </exclusions>
    </dependency>

    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-simple</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>
</project>
