<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.terracotta.dynamic-config.cli</groupId>
    <artifactId>dynamic-config-cli</artifactId>
    <version>5.10.29</version>
    <relativePath>../pom.xml</relativePath>
  </parent>

  <artifactId>dynamic-config-cli-config-tool</artifactId>
  <name>Dynamic Config :: CLI :: Config Tool</name>

  <dependencies>
    <dependency>
      <groupId>org.terracotta.dynamic-config.cli</groupId>
      <artifactId>dynamic-config-cli-support</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>org.terracotta.internal</groupId>
      <artifactId>common-spi</artifactId>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.terracotta.internal</groupId>
      <artifactId>client-runtime</artifactId>
      <scope>provided</scope>
    </dependency>
  </dependencies>
</project>
