= terracotta-platform

image:https://badge.waffle.io/Terracotta-OSS/terracotta-platform.svg?label=ready&title=Ready[link="http://waffle.io/Terracotta-OSS/terracotta-platform"]
image:https://badge.waffle.io/Terracotta-OSS/terracotta-platform.svg?label=in%20progress&title=In%20Progress[link="http://waffle.io/Terracotta-OSS/terracotta-platform"]
image:https://badge.waffle.io/Terracotta-OSS/terracotta-platform.svg?label=under%20review&title=Under%20Review[link="http://waffle.io/Terracotta-OSS/terracotta-platform"]

image:https://terracotta-oss.ci.cloudbees.com/buildStatus/icon?job=terracotta-platform[Terracotta-OSS@Cloudbees, link="https://terracotta-oss.ci.cloudbees.com/job/terracotta-platform/"]

== For Developers

=== License Headers

This project uses the license-maven-plugin to make sure all license headers are present (including all java and xml files) and conform to the root header.txt (Apache 2 License)
Whenever you add a new file, you can automatically have the header added using, at the root level :

     mvn com.mycila:license-maven-plugin:format

Otherwise, you would get such an error while building :

    [ERROR] Failed to execute goal com.mycila:license-maven-plugin:3.0.rc1:check (default) on project platform-root: Some files do not have the expected license header -> [Help 1]

=== Git Commit Messages

* Use the present tense ("Add feature" not "Added feature")
* Use the imperative mood ("Move cursor to..." not "Moves cursor to...")
* Limit the first line to 72 characters or less
* Reference issues and pull requests liberally
* Consider starting the commit message with an applicable emoji:
    - :art: `:art:` when improving the format/structure of the code
    - :racehorse: `:racehorse:` when improving performance
    - :non-potable_water: `:non-potable_water:` when plugging memory leaks
    - :memo: `:memo:` when writing docs
    - :penguin: `:penguin:` when fixing something on Linux
    - :apple: `:apple:` when fixing something on Mac OS
    - :checkered_flag: `:checkered_flag:` when fixing something on Windows
    - :bug: `:bug:` when fixing a bug
    - :fire: `:fire:` when removing code or files
    - :green_heart: `:green_heart:` when fixing the CI build
    - :white_check_mark: `:white_check_mark:` when adding tests
    - :lock: `:lock:` when dealing with security
    - :arrow_up: `:arrow_up:` when upgrading dependencies
    - :arrow_down: `:arrow_down:` when downgrading dependencies
    - :shirt: `:shirt:` when removing linter warnings
    - :speaker: `:speaker:` when adding logging
    - :mute: `:mute:` when reducing logging
    - :bulb: `:bulb:` new idea
    - :construction: `:construction:` work in progress
    - :heavy_plus_sign: `:heavy_plus_sign:` when adding feature
    - :heavy_minus_sign: `:heavy_minus_sign:` when removing feature
    - :snowflake: `:snowflake:` when changing configuration, setting, build file, etc

(adapted from https://github.com/atom/atom/blob/master/CONTRIBUTING.md[Atom guidelines])
