<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <parent>
    <groupId>org.terracotta</groupId>
    <artifactId>platform-root</artifactId>
    <version>5.10-SNAPSHOT</version>
    <relativePath>../</relativePath>
  </parent>
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.terracotta.management</groupId>
  <artifactId>terracotta-management</artifactId>
  <packaging>pom</packaging>

  <modules>
    <module>sequence-generator</module>
    <module>management-model</module>
    <module>management-registry</module>
    <module>cluster-topology</module>
    <module>monitoring-service-api</module>
    <module>monitoring-service</module>
    <module>nms-agent-entity</module>
    <module>nms-entity</module>
    <module>testing/sample-entity</module>
    <module>testing/integration-tests</module>
    <module>testing/doc</module>
  </modules>

  <name>Terracotta Management</name>
  <description>A set of Java modules for management and monitoring, common to several Terracotta products</description>

</project>
