<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.terracotta.diagnostic</groupId>
    <artifactId>diagnostic</artifactId>
    <version>5.10.29</version>
    <relativePath>../pom.xml</relativePath>
  </parent>

  <artifactId>diagnostic-service</artifactId>
  <name>Diagnostic :: Service</name>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.felix</groupId>
        <artifactId>maven-bundle-plugin</artifactId>
        <configuration>
          <archive>
            <manifest>
              <addClasspath>true</addClasspath>
            </manifest>
          </archive>
        </configuration>
      </plugin>
    </plugins>
  </build>

  <dependencies>
    <dependency>
      <groupId>org.terracotta.diagnostic</groupId>
      <artifactId>diagnostic-common</artifactId>
      <version>${project.version}</version>
    </dependency>

    <!-- provided on server -->
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.terracotta</groupId>
      <artifactId>standard-cluster-services</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.terracotta</groupId>
      <artifactId>entity-server-api</artifactId>
      <scope>provided</scope>
    </dependency>

    <dependency>
      <groupId>org.terracotta.diagnostic</groupId>
      <artifactId>diagnostic-service-api</artifactId>
      <version>${project.version}</version>
      <scope>provided</scope>
    </dependency>

    <dependency>
      <groupId>org.terracotta.common</groupId>
      <artifactId>common-test-utilities</artifactId>
      <version>${project.version}</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
</project>
