<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <parent>
    <artifactId>terracotta-management</artifactId>
    <groupId>org.terracotta.management</groupId>
    <version>5.10.29</version>
    <relativePath>../../pom.xml</relativePath>
  </parent>
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.terracotta.management.testing</groupId>
  <artifactId>doc</artifactId>
  <name>Terracotta Management :: Testing :: Doc Use Case</name>

  <dependencies>
    <!-- management client to read the monitoring service-->
    <dependency>
      <groupId>org.terracotta.management</groupId>
      <artifactId>nms-entity-client</artifactId>
      <version>${project.version}</version>
    </dependency>

    <!-- voltron cli -->
    <dependency>
      <groupId>org.terracotta</groupId>
      <artifactId>connection-api</artifactId>
    </dependency>
    <dependency>
      <groupId>org.terracotta.internal</groupId>
      <artifactId>client-runtime</artifactId>
    </dependency>

    <!-- sample entity client -->
    <dependency>
      <groupId>org.terracotta.management.testing</groupId>
      <artifactId>sample-entity</artifactId>
      <version>${project.version}</version>
      <classifier>plugin</classifier>
    </dependency>

    <!-- logging -->
    <dependency>
      <groupId>ch.qos.logback</groupId>
      <artifactId>logback-classic</artifactId>
    </dependency>
  </dependencies>

</project>
