/*
 * Copyright Terracotta, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.05 at 12:10:39 AM EST 
//


package org.terracotta.dynamic_config.xml.topology.config.xmlobjects;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the org.terracotta.dynamic_config.xml.topology.config.xmlobjects package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

  private final static QName _Cluster_QNAME = new QName("http://www.terracotta.org/config/cluster", "cluster");
  private final static QName _ConfigContent_QNAME = new QName("http://www.terracotta.org/config", "config-content");

  /**
   * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.terracotta.dynamic_config.xml.topology.config.xmlobjects
   */
  public ObjectFactory() {
  }

  /**
   * Create an instance of {@link TcCluster }
   */
  public TcCluster createTcCluster() {
    return new TcCluster();
  }

  /**
   * Create an instance of {@link TcStripe }
   */
  public TcStripe createTcStripe() {
    return new TcStripe();
  }

  /**
   * Create an instance of {@link TcNode }
   */
  public TcNode createTcNode() {
    return new TcNode();
  }

  /**
   * Create an instance of {@link TcServerConfig }
   */
  public TcServerConfig createTcServerConfig() {
    return new TcServerConfig();
  }

  /**
   * Create an instance of {@link Loggers }
   */
  public Loggers createLoggers() {
    return new Loggers();
  }

  /**
   * Create an instance of {@link Logger }
   */
  public Logger createLogger() {
    return new Logger();
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link TcCluster }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link TcCluster }{@code >}
   */
  @XmlElementDecl(namespace = "http://www.terracotta.org/config/cluster", name = "cluster", substitutionHeadNamespace = "http://www.terracotta.org/config", substitutionHeadName = "config-content")
  public JAXBElement<TcCluster> createCluster(TcCluster value) {
    return new JAXBElement<TcCluster>(_Cluster_QNAME, TcCluster.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
   */
//  @XmlElementDecl(namespace = "http://www.terracotta.org/config", name = "config-content")
//  public JAXBElement<Object> createConfigContent(Object value) {
//    return new JAXBElement<Object>(_ConfigContent_QNAME, Object.class, null, value);
//  }

}
