<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.terracotta.dynamic-config.cli</groupId>
    <artifactId>dynamic-config-cli</artifactId>
    <version>5.10.29</version>
    <relativePath>../pom.xml</relativePath>
  </parent>

  <artifactId>dynamic-config-cli-upgrade-tools</artifactId>
  <name>Dynamic Config :: CLI :: UpgradeTools</name>

  <dependencies>
    <dependency>
      <groupId>org.terracotta.dynamic-config.cli</groupId>
      <artifactId>dynamic-config-cli-support</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>org.terracotta.dynamic-config.server</groupId>
      <artifactId>dynamic-config-configuration-repository</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>org.terracotta</groupId>
      <artifactId>terracotta-utilities-tools</artifactId>
      <exclusions>
        <exclusion>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </exclusion>
    </exclusions>
    </dependency>
    <dependency>
      <groupId>ch.qos.logback</groupId>
      <artifactId>logback-classic</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>javax.xml.bind</groupId>
        <artifactId>jaxb-api</artifactId>
        <version>2.3.1</version>
    </dependency>
    <!-- server apis -->
    <dependency>
      <groupId>org.terracotta.internal</groupId>
      <artifactId>tc-config-parser</artifactId>
    </dependency>
    <dependency>
      <groupId>org.terracotta</groupId>
      <artifactId>entity-server-api</artifactId>
    </dependency>

    <!-- server plugins -->
    <dependency>
      <groupId>org.terracotta.management</groupId>
      <artifactId>monitoring-service-api</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>org.terracotta</groupId>
      <artifactId>data-root-resource</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>org.terracotta</groupId>
      <artifactId>offheap-resource</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>org.terracotta</groupId>
      <artifactId>lease-entity-server</artifactId>
      <version>${project.version}</version>
    </dependency>
  </dependencies>
</project>
