////
    Copyright Terracotta, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////
:toc:
:toclevels: 5

= Migrating from older Terracotta versions to 10.7

This document describes the process of migrating from earlier Terracotta (10.5 and older) releases to release 10.7.

== Background
A major feature of the 10.7 release is dynamic configuration of the Terracotta cluster, which changes cluster startup and configuration mechanisms.
This documents briefly lists the new concepts, tooling information, and the steps to be followed to migrate from an earlier 10.x to a 10.7 cluster.
The term "server" has been replaced by "node", as the latter is the more appropriate term to denote individual hosts in a cluster.
All mentions of "node" henceforth can be mentally transformed to mean "server".

== What has changed
. *Node startup mechanism*
+
`start-tc-server.(bat|sh)` does not support a tc-config XML file anymore. Several new options have been added to this script.
More information can be found in the <<startup-script, `startup script`>> section.

. *Cluster configuration format*
+
Cluster configuration can no more be specified using tc-config XML files. The old tc-configs can be migrated to the
new configuration format using <<config-converter-tool, config converter tool>>.

. *Cluster configuration mechanism*
+
Cluster tool `configure` command has been removed in favor of <<config-tool-activate, config tool `activate`>> command.
Cluster tool `reconfigure` command has been removed in favor of <<config-tool-set, config tool `set`>> command.

== Important Terms and Concepts
. *Config properties file*
+
A Java properties file containing settings for the entire cluster.
Can be exported from an existing cluster and imported on to a new cluster.
Can be thought of as a single file which replaces multiple tc-config XML files
(where each tc-config corresponded to one stripe in the cluster).

. *Config directory*
+
A non-editable, on-disk, per-node directory of node configuration information.
Maintains a record of the configuration changes done on the node as well as the license in use for the node.

[[config-converter-tool]]
== Using config converter tool
Config converter tool can be used to convert from tc-config XML files used with Terracotta versions upto 10.5 to the new configuration format.
The tool can be located under `tools/upgrade-tools/bin` in the product installation directory, and has the following usage:

[source,bash]
----
> config-converter.(bat|sh) convert -c <tc-config>,<tc-config>... ( -t directory [-l <license-file>] -n <new-cluster-name> | -t properties [-n <new-cluster-name>]) [-d <destination-dir>] [-f]
----

When the output format is config directory (i.e. `-t directory` or no `-t` specification), a license file can be supplied.

NOTE: In a fresh install of Terracotta using the Software AG installer, the license file can be found under the Terracotta installation root.

This way, the generated config directory will be ready-for-use by Terracotta clients. This is the recommended output format.
Note that there is no change in the license file, or the licensing policies.
Thus, existing Terracotta licenses will continue to work with 10.7 until their expiration.

When the output format is config properties (i.e. `-t properties`), the generated config properties file contains
information from all the tc-config XML files, and can also be used to start up the nodes.
However, an additional cluster activation step may be required after the migrated cluster is started using this config properties file.

[[create-permanent-entity-script]]
== Permanent Entity Creation Script
If you want to use old data with 10.7 server, you need to run this script. Here -s option must contain one hostport per stripe to ensure that missing entities are created across all the stripes.

[source,bash]
----
> create-permanent-entities.(bat|sh) -s <hostname[:port]>,...
----

[[startup-script]]
== Updates to the `start-tc-server` script
The `start-tc-server` script does not support tc-config XML files anymore. Instead, it supports several options which let
you specify a node's configuration via the command itself.
Here's the full list of supported options along with default values, obtained from the output of `start-tc-server.(bat|sh) --help` command:

[source,bash]
----
> ./start-tc-server.sh -h
usage: start-tc-server [options]
Startup options:
    -c,--consistency-on-startup    preserve data consistency on startup
    -h,--help                      display help

Configuration options:
    -u, --audit-log-dir              security audit log directory
    -z, --authc                      security authentication setting (file|ldap|certificate)
    -b, --backup-dir                 node backup directory
    -a, --bind-address               node bind address for port. Default: 0.0.0.0
    -i, --client-lease-duration      client lease duration. Default: 150s
    -R, --client-reconnect-window    client reconnect window. Default: 120s
    -N, --cluster-name               cluster name
    -r, --config-dir                 node configuration directory. Default: %H/terracotta/config
    -f, --config-file                configuration properties file
    -d, --data-dirs                  data directory. Default: main:%H/terracotta/user-data/main
    -y, --failover-priority          failover priority setting (availability|consistency)
    -A, --group-bind-address         node bind address for group port. Default: 0.0.0.0
    -g, --group-port                 node port used for intra-stripe communication. Default: 9430
    -s, --hostname                   node host name. Default: %h
    -L, --log-dir                    node log directory. Default: %H/terracotta/logs
    -m, --metadata-dir               node metadata directory. Default: %H/terracotta/metadata
    -n, --name                       node name. Default: <randomly-generated>
    -o, --offheap-resources          offheap resources. Default: main:512MB
    -p, --port                       node port. Default: 9410
    -S, --public-hostname            public node host name
    -P, --public-port                public node port
    -D, --repair-mode                node repair mode (true|false)
    -x, --security-dir               security root directory
    -t, --ssl-tls                    ssl-tls setting (true|false). Default: false
    -T, --tc-properties              tc-properties
    -w, --permit-list                security permit list (true|false). Default: false

Allowed substitution parameters:
    %v    version of the operating system. Same as java 'os.version' property
    %h    host name of the machine
    %H    home directory of the user. Same as java 'user.home' property
    %i    IP address of the machine corresponding to localhost
    %n    username of the user. Same as java 'user.name' property
    %o    name of the operating system. Same as java 'os.name' property
    %a    architecture of the machine. Same as java 'os.arch' property
    %c    canonical host name of the machine
    %t    temporary directory of the machine. Same as java 'java.io.tmpdir' property
    %d    unique temporary directory
    %D    date stamp corresponding to current time
----

A node can directly start in activated state if it was started with a fully-formed config directory,
obtained from <<config-converter-tool, config converter tool>>,
or formed after <<config-tool-activate, config tool `activate`>> was executed in a previous run.

Otherwise, <<config-tool-activate, config tool `activate`>> command will need to be run after the cluster topology has
been created using <<config-tool-attach, config tool `attach`>> command.

[[config-tool]]
== Using config tool
Config tool provides a suite of commands used for managing the cluster topology and configuration, among other things.
The tool can be located under `tools/bin` in the product installation directory.
The following is an overview of important config tool commands:

[[config-tool-attach]]
=== `attach` command
The `attach` command builds a cluster by constructing stripes from nodes, and cluster from stripes respectively.
Currently, it works prior to cluster activation only. The work to allow dynamic addition of nodes from the cluster post
cluster activation is underway, and will be delivered in 10.7 release itself.
In near future, this command will allow dynamic addition of nodes to the cluster.

[source,bash]
----
> config-tool.(bat|sh) attach [-t node|stripe] -d <hostname[:port]> -s <hostname[:port]> [-f] [-W <restart-wait-time>] [-D <restart-delay>]
----

[[config-tool-detach]]
=== `detach` command
The `detach` command allows removal of nodes from stripes, and stripes from cluster respectively.
Currently, it works prior to cluster activation only. The work to allow dynamic removal of nodes from the cluster post
cluster activation is underway, and will be delivered in 10.7 release itself.

[source,bash]
----
> config-tool.(bat|sh) [-t node|stripe] -d <hostname[:port]> -s <hostname[:port]> [-f] [-W <stop-wait-time>] [-D <stop-delay>]
----

[[config-tool-activate]]
=== `activate` command
The `activate` command makes a cluster ready to be used by Terracotta clients.
`activate` should be run once the topology has been created using <<config-tool-attach, `attach`>> command.

[source,bash]
----
> config-tool.(bat|sh) activate -s <hostname[:port]> -f <config-file> [-n <cluster-name>] [-R] [-l <license-file>] [-W <restart-wait-time>] [-D <restart-delay>]
----

[[config-tool-set]]
=== `set` command
The `set` command updates configuration settings on individual nodes, stripes or the entire cluster, depending on the specified namespace.
Some settings can be updated dynamically, whereas others require a cluster restart.
Note that not all settings (e.g. node's hostname) can be updated using this command.

[source,bash]
----
> config-tool.(bat|sh) set -s <hostname[:port]> -c <[namespace:]property=value>,<[namespace:]property=value>...
----

[[config-tool-unset]]
=== `unset` command
This unset command updates the settings on individual nodes, stripes or the entire cluster by removing the value associated with them.
Some settings can be updated dynamically, whereas others require a cluster restart.
Note that not all settings (e.g. node's hostname) can be unset using this command.

[source,bash]
----
> config-tool.(bat|sh) unset -s <hostname[:port]> -c <[namespace:]property>,<[namespace:]property>...
----

[[migration-steps]]
== Steps to be followed for migration of an existing Terracotta 10.x (10.5 and older) cluster
. Shut down all Terracotta clients and ensure no critical operations (like backup) are running on the cluster.
Note down the hosts the nodes are running on.
. Use the cluster tool `shutdown` command to shut down the Terracotta cluster.
. Use the <<config-converter-tool, config converter tool>> to convert tc-config.xml files to config directory format.
. Copy the config directories generated from the step above to the hosts from the first step.
. Start the nodes using <<startup-script, startup script>> with option `-r`, supplying the config directory path.
. Use the <<create-permanent-entity-script, create-permanent-entity-script>> in case you want to use the old data with 10.7 server. Ensure that you run this script before connecting any clients.
. Replace the old client jars with 10.7 jars in the client classpath.
. Connect the clients back with the cluster.
