////
 Copyright (c) 2011-2020 Software AG, Darmstadt, Germany and/or Software AG USA Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors.
 Use, reproduction, transfer, publication or disclosure is prohibited except as specifically provided for in your License Agreement with Software AG.
////
= Dynamic Config: Nomad Command String Structure

== Objective

We need to send commands from the cluster tool to the servers in the cluster to instruct the servers to make
configuration changes.

== Discussion

=== Human-readable
The commands should have human-readable representations so that, when they are persisted in the sanskrit repository,
they can be read, for easy support.

=== Parameter complexity
Some commands will require only simple parameters. For example, increasing the size of an offheap resource requires only
the name of the offheap resource and the new size.

However, some commands will require more complex parameters. For example, a command to add a passive to a stripe will
require, amongst other things, a mapping from data root names to paths. Also, if the new server will use the command to
configure itself as part of the cluster (which seems sensible) then the command must also contain the full topology
information. This would require the cluster tool to fetch the topology information from the cluster before creating the
command.

=== Command applicability
Different commands change the configuration of different sets of servers. For example, a command to increase the size
of an offheap resource should change the size of that offheap on all servers, whereas a command to set the path of a
data-root applies to a single server and a command to add a passive applies to all the servers in a stripe. However,
every server will make a change to its recorded configuration because that configuration includes the configuration of
all servers.

=== Multiple commands
There may be cases where multiple commands should be executed as part of the same logical change (for example to change
the authentication scheme and to change the security root directory at the same time). This might not be supported by
the current design for the cluster tool command line, however the intention is to build a wizard that provides better
usability and possibly more power.

=== Sensitive information
Some configuration may contain sensitive information such as private keys or passwords. At the moment all such
configuration is placed in files and protected using filesystem permissions. However, if we allow commands to provide
such information then the sanskrit repository becomes something that must be secured with filesystem permissions and
sharing the repository with Software AG support becomes more difficult. We will side-step this issue for now by not
allowing a file upload command. Users must place such files on the server themselves. The configuration commands will
only specify the paths to those files (e.g. security root directory path).

== Design

=== Formal definition
We will use JSON to represent the command. It will have the following structure in (pseudo-BNF):

 <command-string> ::= "[" <list-of-commands> "]"
 <list-of-commands> ::= <command> | <command>"," <list-of-commands>
 <commmand> ::= "{
   '"operation'": '"<operation-name>'",
   '"applicability'": <applicability>,
   '"parameters'": <parameters>
 }"
 <operation-name> ::= "add-alter-offheap" | "add-passive" | etc.
 <applicability> ::= <cluster-applicability> | <stripe-applicability> | <server-applicability>
 <cluster-applicability ::= "{
   '"type'": '"cluster'"
 }"
 <stripe-applicability> ::= "{
   '"type'": '"stripe'",
   '"name'": '"<stripe-name>'"
   }"
 <server-applicability> ::= "{
   '"type'": '"server'",
   '"name'": '"<server-name>'"
 }"

where ```<stripe-name>``` is a valid stripe name, ```<server-name>``` is a valid server name and ```<parameters>``` is
a JSON object containing data relevant to the command.

=== Examples

==== Increase offheap size

 [
   {
     "operation": "add-alter-offheap",
     "applicability": {
       "type": "cluster"
     },
     "parameters": {
       "offheap-name": "offheap1",
       "new-size": 104857600
     }
   }
 ]

==== Add passive

 [
   {
     "operation": "add-passive",
     "applicability": {
       "type": "stripe",
       "name": "stripe1"
     },
     "parameters": {
       "server-name": "server5",
       "log-path": "/path/for/log",
       "host": "dc1-server-42",
       "port": 9410,
       "group-port": 9430,
       "offheap-resources": [
         {
           "name": "offheap1",
           "size": 104857600
         },
         {
           "name": "offheap2",
           "size": 104857600
         }
       ],
       "data-roots": [
         {
           "name": "platform",
           "use-for-platform": "true",
           "path": "/path/for/data1"
         },
         {
           "name": "store",
           "use-for-platform": "false",
           "path": "/path/for/data2"
         }
       ],
       "current-topology": <full-topology>
     }
   }
 ]

Note that given the full topology is included in the ```current-topology``` parameter, it may not be necessary to
include the details of offheap-resources and data-root because the new passive should match the other servers. However
the data root paths are required.

=== Extent of this design

This design covers the top level layout of the command structure. It does not specify the names of the commands or the
parameters that may be required for each individual command. This is work that should be done when implementing each
command.

Specifically, the command names and parameter structures shown in the examples are not intended to form part of this
design, they are merely to show what such commands could look like.